Byoungjuseo
Bom-start/ReadingRecord pull request #94
Opened 2023-05-19 23:36 UTC by zaragit

#### 📖 어떤 책을 읽으셨어요?
혼자서 공부하는 컴퓨터 구조+운영체제

#### 🖋 이번에 정리한 챕터를 알려주세요
챕터 1~3까지 읽었습니다.

2023-07-22 01:16 UTC, youngjinmo commented
컴퓨터 구조 + 운영체제 PR에 클린코드 정리된 내용이 함께 들어가있군요!
파일별로 커밋을 다시 쪼갠 후, PR을 분리해보시죠!!
컴퓨터구조 부문은 LGTM입니다! (Looks Good To Me) 😁

2023-07-22 01:16 UTC, youngjinmo requested changes
컴퓨터 구조 + 운영체제 PR에 클린코드 정리된 내용이 함께 들어가있군요!
파일별로 커밋을 다시 쪼갠 후, PR을 분리해보시죠!!
컴퓨터구조 부문은 LGTM입니다! (Looks Good To Me) 😁

2023-07-22 05:22 UTC, zaragit commented
클린코드 부분만 분리했습니다!

2023-07-26 03:58 UTC, youngjinmo approved these changes
꼼꼼히 정리해주신덕분에 빠르게 다시 읽어볼 수 있었습니다! 감사합니다!! 👍

2023-07-29 23:07 UTC, merged